name: modern-mosaics
region: lon

services:
  - name: web
    github:
      repo: welathfindrr13/modern-mosaics
      branch: main
      deploy_on_push: true
    source_dir: /
    run_command: npm run start
    build_command: npm ci && npm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xs
    http_port: 3000
    health_check:
      http_path: /api/health
      initial_delay_seconds: 20
      period_seconds: 15
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
